Repository holidaycheck/healthcheck-ping, pull requests merged in 2018-07, with the labels that each got.

#39 Drop nodejs support for versions < 8
  .travis.yml
Labels: breaking

#40 Update all dependencies
  package.json
Labels: upgrade

#38 📃 Add TypeScript type declarations
  package.json
  types/healthcheck-ping-tests.ts
  types/index.d.ts
  types/tsconfig.json
  types/tslint.json
Labels: feature

#41 🐛 Fix TypeScript declaration file
  types/index.d.ts
Labels: bug

#43 Use nyc instead of istanbul
  .istanbul.yml
  package.json
Labels: refactor

#42 🗑 Remove supertest-as-promised
  package.json
  test/functional/healthcheckMiddlewareSpec.js
Labels: refactor
